###https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html

#ansible.builtin.debug - This module prints statements during execution and
#can be useful for debugging variables or expressions without necessarily halting the playbook.

#
- name: Demo on vars play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Demo on vars task level
  hosts: all
  connection: local
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: task.example.com

- name: Demo on vars from file play level
  hosts: all
  connection: local
  vars_files:
    - sample-var.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Vars from inventory file
  hosts: all
  connection: local

  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

