###https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html

#ansible.builtin.debug - This module prints statements during execution and
#can be useful for debugging variables or expressions without necessarily halting the playbook.

#PLAY LEVEL VARIABLES
- name: Demo on vars play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

#TASK LEVEL VARIABLES

- name: Demo on vars task level
  hosts: all
  connection: local
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: task.example.com

#VARIABLES FROM A FILE
- name: Demo on vars from file play level
  hosts: all
  connection: local
  vars_files:
    - sample-var.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

#INVENTORY FILE VARIABLES
- name: Vars from inventory file
  hosts: all
  connection: local

  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

#ANSIBLE PRE-DEFINED VARIABLES

- name: pre-defined variables
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: print hostname
      ansible.builtin.debug:
        msg: hostname= {{ansible_hostname}}

#ansible run-time variables

- name: demo on run-time variables
  hosts: all
  connection: local

  tasks:
    - name: execute shell command
      ansible.builtin.shell: uptime
      register: out

    - name: set a fact
      ansible.builtin.set_fact:
        UPTIME: "{{out.stdout}}"

    - name: print out
      ansible.builtin.debug:
        msg: "{{UPTIME}}"


